include:
  - ./volumes/n8n-phd/docker-compose.yml
  - ./volumes/n8n-sandbox/docker-compose.yml
  - ./volumes/n8n-demo/docker-compose.yml
  - ./volumes/n8n-personal/docker-compose.yml

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - n8n-phd
      - n8n-sandbox
      - n8n-demo
      - n8n-personal
    restart: always
