services:
  n8n-personal:
    build: .
    container_name: n8n-personal
    restart: always
    environment:
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=personal.n8ncluster.co.uk
      - N8N_PROTOCOL=https
      - N8N_URL=https://personal.n8ncluster.co.uk
      - N8N_WEBHOOK_URL=https://personal.n8ncluster.co.uk
      - N8N_EDITOR_BASE_URL=https://personal.n8ncluster.co.uk
      - N8N_ALLOWED_ORIGINS=*
    volumes:
      - ../../volumes/n8n-personal:/home/node/.n8n
