services:
  n8n-phd:
    image: n8nio/n8n:latest
    container_name: n8n-phd
    restart: always
    environment:
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=phd.n8ncluster.co.uk
      - N8N_PROTOCOL=https
      - N8N_URL=https://phd.n8ncluster.co.uk
      - N8N_WEBHOOK_URL=https://phd.n8ncluster.co.uk
      - N8N_EDITOR_BASE_URL=https://phd.n8ncluster.co.uk
      - N8N_ALLOWED_ORIGINS=*
    volumes:
      - ../../volumes/n8n-phd:/home/node/.n8n
