services:
  n8n-phd:
    image: n8nio/n8n:latest
    container_name: n8n-phd
    restart: always
    environment:
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://phd.localhost/
      - N8N_EDITOR_BASE_URL=http://phd.localhost/
    volumes:
      - ../../volumes/n8n-phd:/home/node/.n8n
